from litemapy import Schematic, Region, BlockState
from input_utils import get_polygon_nodes, get_building_params
from wall_utils import choose_wall_style_layers
from builder import build_skyscraper

def main():
    print("欢迎使用Skyscraper creater！")
    nodes = get_polygon_nodes()
    wall_layers, wall_pattern, wall_density = choose_wall_style_layers()
    (
        floor_height, total_height, partition, x_parts, z_parts, partition_blocks,
        slab_thickness, ceiling_blocks, light_block, light_density, floor_block
    ) = get_building_params()
    reg = build_skyscraper(
        nodes, wall_layers, floor_height, total_height, partition,
        x_parts, z_parts, partition_blocks,
        ceiling_blocks, light_block, light_density,
        wall_pattern=wall_pattern, wall_density=wall_density
    )
    name = input("请输入schematic名称：")
    author = input("请输入作者名：")
    desc = "Generated by Skyscraper creater"
    schem = reg.as_schematic(name=name, author=author, description=desc)
    schem.save(f"{name}.litematic")
    print(f"已保存为{name}.litematic")

if __name__ == "__main__":
    main()
